import initSqlJs, { type SqlJsStatic, type Database } from 'sql.js';
import { drizzle, type SQLJsDatabase } from 'drizzle-orm/sql-js';
import { saveDatabase, loadDatabase, deleteDatabase } from './storage';
import * as schema from './schema';
// Import the pre-exported migrations JSON (generated by scripts/export-migrations.ts)
import migrations from './migrations/export.json';

let _SQL: SqlJsStatic | null = null;
let _db: SQLJsDatabase<typeof schema> | null = null;
let _sqlDb: Database | null = null;

export async function getDb(): Promise<{
  db: SQLJsDatabase<typeof schema>;
  sqlDb: Database;
}> {
  if (_db && _sqlDb) return { db: _db, sqlDb: _sqlDb };

  // 1. Init sql.js (load WASM)
  if (!_SQL) {
    _SQL = await initSqlJs({
      locateFile: (file) => `/${file}`,
    });
  }

  // 2. Load saved database from IndexedDB, or create a fresh one
  const saved = await loadDatabase();

  if (saved && saved.byteLength > 0) {
    _sqlDb = new _SQL.Database(saved);
  } else {
    _sqlDb = new _SQL.Database();
  }

  // 3. Create Drizzle instance
  _db = drizzle(_sqlDb, { schema });

  // 4. Apply migrations
  //    The SQLite sync dialect's migrate() reads the MigrationMeta[] array
  //    directly (no filesystem needed) and uses a __drizzle_migrations table
  //    to track what's already been applied — idempotent.
  //    (dialect & session are @internal; cast through any to access them)
  ;( _db as any ).dialect.migrate(migrations, ( _db as any ).session, {
    migrationsTable: '__drizzle_migrations',
  });

  // 5. Persist the migrated database back to IndexedDB
  await persistNow();

  return { db: _db, sqlDb: _sqlDb };
}

/**
 * Nuke the IndexedDB database and reset the in-memory cache so the
 * next {@link getDb()} call re-migrates from scratch.
 */
export async function nukeDb(): Promise<void> {
  _SQL = null;
  _db = null;
  _sqlDb = null;
  await deleteDatabase();
}

/** Serialize the in-memory database to IndexedDB. */
export async function persistNow(): Promise<void> {
  if (!_sqlDb) return;
  const data = _sqlDb.export();
  await saveDatabase(data);
}
